version: "3.8"

services:
  db:
    image: postgres:13
    container_name: test_ci_cd-db-1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=base_test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=base_test
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app

  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./front:/usr/src/app

volumes:
  postgres-data:
