name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup-and-build:
    runs-on: ubuntu-latest

    steps:
      # Étape pour récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape pour configurer Node.js dans la version spécifiée
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Étape pour installer les dépendances et construire le frontend
      - name: Install and build front-end
        working-directory: ./front
        run: |
          npm install
          npm run build

      # Étape pour nettoyer et construire l'API
      - name: Clean and build API
        working-directory: ./api
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps || echo "Warnings during npm install"
          npm run build

  docker:
    runs-on: ubuntu-latest
    needs: setup-and-build

    steps:
      # Étape pour récupérer de nouveau le code, si nécessaire pour le job Docker
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape pour configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape pour installer Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      # Étape pour arrêter les conteneurs existants et construire les images Docker
      - name: Build and push Docker images
        run: |
          docker-compose down
          docker-compose build

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      # Étape pour déployer l'application sur un VPS via SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            DEPLOY_DIR=~/api

            if [ ! -d $DEPLOY_DIR ]; then
              mkdir -p $DEPLOY_DIR
              git clone https://github.com/Florence-Martin/Test_CI_CD.git $DEPLOY_DIR || exit 10
              cd "$DEPLOY_DIR"
            else
              cd $DEPLOY_DIR
              sudo git pull origin main || exit 11
            fi

            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}" > .env

            sudo docker-compose down -v || exit 20
            sudo docker-compose up -d || exit 30
