name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and build front
        working-directory: ./front
        run: |
          npm install
          npm run build

      - name: Clean install dependencies for api
        working-directory: ./api
        run: |
          rm -rf node_modules
          rm package-lock.json
          npm install --legacy-peer-deps
          npm run build

      - name: Run linter for front
        working-directory: ./front
        run: |
          npm run lint

      # Comment or remove the following lines to disable the linter for api
      # - name: Run linter for api
      #   working-directory: ./api
      #   run: |
      #     npm run lint

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Installer Docker Compose s'il n'est pas déjà installé
            if ! command -v docker-compose &> /dev/null
            then
              sudo apt-get update
              sudo apt-get install -y curl jq
              sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Cloner le dépôt si le répertoire n'existe pas
            if [ ! -d "~/myapp/.git" ]; then
              git clone https://github.com/Florence-Martin/Test_CI_CD.git ~/myapp
            fi

            cd ~/myapp
            git pull origin main
            sudo docker-compose down
            sudo docker-compose up -d --build
